import type { Cottage } from '@/types/cottage.ts'

export default function () {
  const cottages = useState<Cottage[]>('cottages', () => [
    {
      id: '1',
      title: 'Sjöstugan',
      description: '',
      image: '/images/ai-generated-8613213_640.jpg',
      address: 'Strandvägen 1',
      postalCode: '12345',
      city: 'Sjöstad',
      beds: 4,
      rooms: 2,
    },
    {
      id: '2',
      title: 'Skogshemmet',
      description: '',
      image: '/images/building-69768_640.jpg',
      address: 'Skogsvägen 2',
      postalCode: '23456',
      city: 'Skogsby',
      beds: 6,
      rooms: 3,
    },
    {
      id: '3',
      title: 'Havsbris',
      description: '',
      image: '/images/cabin-5623592_640.jpg',
      address: 'Havsgatan 3',
      postalCode: '34567',
      city: 'Havshamn',
      beds: 8,
      rooms: 4,
    },
    {
      id: '4',
      title: 'Fjällstugan',
      description: '',
      image: '/images/cottage-1874633_640.jpg',
      address: 'Fjällvägen 4',
      postalCode: '45678',
      city: 'Fjällbyn',
      beds: 6,
      rooms: 3,
    },
    {
      id: '5',
      title: 'Ängslunden',
      description: '',
      image: '/images/cottage-8474753_640.jpg',
      address: 'Ängsvägen 5',
      postalCode: '56789',
      city: 'Ängsby',
      beds: 4,
      rooms: 2,
    },
    {
      id: '6',
      title: 'Sjöboden',
      description: '',
      image: '/images/holiday-home-177401_640.jpg',
      address: 'Sjögatan 6',
      postalCode: '67890',
      city: 'Sjöby',
      beds: 8,
      rooms: 4,
    },
    {
      id: '7',
      title: 'Strandstugan',
      description: '',
      image: '/images/house-3786593_640.jpg',
      address: 'Strandvägen 7',
      postalCode: '78901',
      city: 'Strandstad',
      beds: 6,
      rooms: 3,
    },
    {
      id: '8',
      title: 'Skogsgläntan',
      description: '',
      image: '/images/mountains-1587287_640.jpg',
      address: 'Skogsvägen 8',
      postalCode: '89012',
      city: 'Skogshamn',
      beds: 4,
      rooms: 2,
    },
    {
      id: '9',
      title: 'Havsnära',
      description: '',
      image: '/images/cabin-5842940_640.jpg',
      address: 'Havsgatan 9',
      postalCode: '90123',
      city: 'Havsby',
      beds: 8,
      rooms: 4,
    },
    {
      id: '10',
      title: 'Fjällvinden',
      description: '',
      image: '/images/winter-4727668_640.jpg',
      address: 'Fjällvägen 10',
      postalCode: '01234',
      city: 'Fjällstad',
      beds: 6,
      rooms: 3,
    },
    {
      id: '11',
      title: 'Ängshagen',
      description: '',
      image: '/images/wooden-house-5990155_640.jpg',
      address: 'Ängsvägen 11',
      postalCode: '12340',
      city: 'Ängsstad',
      beds: 4,
      rooms: 2,
    },
    {
      id: '12',
      title: 'Sjöutsikten',
      description: '',
      image: '/images/stilt-house-7851833_640.jpg',
      address: 'Sjögatan 12',
      postalCode: '23450',
      city: 'Sjöhamn',
      beds: 8,
      rooms: 4,
    },
  ])

  const findCottageById = (id: string) => {
    return cottages.value.find(cottage => cottage.id === id)
  }

  return {
    cottages,
    findCottageById,
  }
}
